@startuml
hide circle
hide methods

class schema_version {
version: DB schema version
}

class killed_test_case {
    id          INTEGER PRIMARY KEY,
---
- location: optional info helping a user
locate the mutant
}
killed_test_case "mut_id" --> "id" mutation
killed_test_case "tc_id" --> "id" all_test_case

class all_test_case {
    id          INTEGER PRIMARY KEY,
---
- name: name of the test
}

class mutation_status {
    id          INTEGER PRIMARY KEY,
---
- status: status of the mutant
- time: spent on testing the mutant
- test_cnt: nr of times the mutant is tested
- update_ts: date+time the status updated
- added_ts: date+time the mutant where found
- checksum: of the mutation of the src
}

class mutation {
    id      INTEGER PRIMARY KEY,
---
- kind: type of mutant,
}
mutation "mp_id" --> "id" mutation_point
mutation "st_id" --> "id" mutation_status

class mutation_point {
    id              INTEGER PRIMARY KEY,
---
- offset: byte range
- line+column: in the src file
}
mutation_point "file_id" --> "id" files

class nomut {
id  INTEGER PRIMARY KEY,
---
line
}
nomut "file_id" --> "id" files

class files {
    id          INTEGER PRIMARY KEY,
    path        TEXT NOT NULL,
---
- checksum: 128bit of the file
- lang: type of language the file is
}
@enduml
