@startuml
hide empty description

[*] -> Initialize

Initialize -> SanityCheck

SanityCheck --> Error : failed
SanityCheck --> ParseStdin : fromStdin
SanityCheck -> PreCompileSut

ParseStdin -> PreCompileSut

PreCompileSut --> Error : failed
PreCompileSut --> FindTestCmds : hasTestCmdDir
PreCompileSut --> ChooseMode

FindTestCmds -> ChooseMode

ChooseMode --> AnalyzeTestCmdForTestCase : hasAnalyzer
ChooseMode --> PullRequest : hasConstraint
ChooseMode --> CheckMutantsLeft

PullRequest -> CheckMutantsLeft

AnalyzeTestCmdForTestCase --> UpdateAndResetAliveMutants

UpdateAndResetAliveMutants --> CheckMutantsLeft

UpdateTimeout --> CleanupTempDirs

CleanupTempDirs --> NextSchemata
CleanupTempDirs --> NextPullRequestMutant : hasConstraint

CheckMutantsLeft --> Done : allTested && !resetOld
CheckMutantsLeft --> MeasureTestSuite

MeasureTestSuite --> Error : unreliable
MeasureTestSuite --> SetMaxRuntime

SetMaxRuntime --> LoadSchematas

LoadSchematas --> UpdateTimeout

CheckRuntime --> UpdateTimeout
CheckRuntime --> Done : runtime>max

NextPullRequestMutant --> PreMutationTest
NextPullRequestMutant --> Done : allTested

NextSchemata --> PreSchemata : hasSchema
NextSchemata --> NextMutant
PreSchemata --> SanityCheckSchemata
SanityCheckSchemata --> SchemataRestore : failed
SanityCheckSchemata --> SchemataTest : ok
SchemataTest --> SchemataTest
SchemataTest --> SchemataTestResult : done
SchemataTestResult --> SchemataRestore
SchemataRestore --> CheckRuntime

NextMutant --> CheckTimeout : allTested
NextMutant --> PreMutationTest
PreMutationTest --> MutationTest
MutationTest --> HandleTestResult : next
MutationTest --> Error : error
MutationTest --> MutationTest

HandleTestResult --> CheckRuntime

CheckTimeout --> ResetOldMutant : unchanged
CheckTimeout --> UpdateTimeout

ResetOldMutant --> UpdateTimeout
ResetOldMutant --> Done : nr >= max

Done --> Done

Error --> Error
@enduml
