@startuml
hide empty description

[*] -> Initialize

Initialize -> SanityCheck

SanityCheck --> Error : failed
SanityCheck --> ParseStdin : fromStdin
SanityCheck -> PreCompileSut

ParseStdin -> PreCompileSut

PreCompileSut --> Error : failed
PreCompileSut --> FindTestCmds : hasTestCmdDir
PreCompileSut --> ChooseMode

FindTestCmds -> ChooseMode

ChooseMode --> AnalyzeTestCmdForTestCase : hasAnalyzer
ChooseMode --> PullRequest : hasConstraint
ChooseMode --> CheckMutantsLeft

PullRequest -> CheckMutantsLeft

AnalyzeTestCmdForTestCase --> UpdateAndResetAliveMutants

UpdateAndResetAliveMutants --> CheckMutantsLeft

UpdateTimeout --> OverloadCheck

OverloadCheck --> CheckStopCond : sleep
OverloadCheck --> Done : halt
OverloadCheck --> ContCheckTestSuite : ok

ContCheckTestSuite --> Cleanup : ok
ContCheckTestSuite --> Error : fail

Cleanup --> NextSchemata
Cleanup --> CheckPullRequestMutant : hasConstraint

CheckMutantsLeft --> ChecksumTestCmds : checksum
CheckMutantsLeft --> MeasureTestSuite : !allTested || resetOld
CheckMutantsLeft --> Done : !resetOld && allTested

ChecksumTestCmds --> MeasureTestSuite

MeasureTestSuite --> Error : unreliable
MeasureTestSuite --> Coverage : useCov
MeasureTestSuite --> LoadSchematas : !useCov

Coverage --> PropagateCov : !error
Coverage --> LoadSchematas : error
PropagateCov --> LoadSchematas

LoadSchematas --> ResetOldMutant

ResetOldMutant --> UpdateTimeout

CheckStopCond --> UpdateTimeout
CheckStopCond --> Done : runtime>max

CheckPullRequestMutant --> NextMutant
CheckPullRequestMutant --> Done : allTested

NextSchemata --> SchemataTest : hasSchema
NextSchemata --> Done : !hasSchema && user
NextSchemata --> NextMutant
SchemataTest --> CheckStopCond : done

NextMutant --> CheckTimeout : allTested
NextMutant --> MutationTest
MutationTest --> HandleTestResult : next
MutationTest --> Error : error
MutationTest --> MutationTest

HandleTestResult --> CheckStopCond

CheckTimeout --> Done : unchanged
CheckTimeout --> UpdateTimeout : changed

Done --> SchemataPruneUsed
SchemataPruneUsed --> SaveMutationScore
SaveMutationScore --> Stop

Error --> Stop
@enduml
