@startuml
hide empty description

[*] -> Initialize

Initialize -> SanityCheck

SanityCheck --> Error : failed
SanityCheck --> ParseStdin : fromStdin
SanityCheck -> PreCompileSut

ParseStdin -> PreCompileSut

PreCompileSut --> Error : failed
PreCompileSut --> FindTestCmds : hasTestCmdDir
PreCompileSut --> UpdateTestCmd

FindTestCmds -> UpdateTestCmd

UpdateTestCmd -> ChooseMode

ChooseMode --> AnalyzeTestCmdForTestCase : hasAnalyzer
ChooseMode --> PullRequest : hasConstraint
ChooseMode --> RetestOldMutant : resetOld
ChooseMode --> IncreaseFilePrio

PullRequest -> IncreaseFilePrio

IncreaseFilePrio --> CheckMutantsLeft

AnalyzeTestCmdForTestCase --> UpdateAndResetAliveMutants

UpdateAndResetAliveMutants --> RetestOldMutant : resetOld
UpdateAndResetAliveMutants --> IncreaseFilePrio : resetOld
RetestOldMutant --> IncreaseFilePrio

UpdateTimeout --> OverloadCheck

OverloadCheck --> CheckStopCond : sleep
OverloadCheck --> Done : halt
OverloadCheck --> ContCheckTestSuite : ok

ContCheckTestSuite --> Cleanup : ok
ContCheckTestSuite --> Error : fail

Cleanup --> NextSchemata
Cleanup --> CheckPullRequestMutant : hasConstraint

CheckMutantsLeft --> ChecksumTestCmds : checksum
CheckMutantsLeft --> MeasureTestSuite : !allTested
CheckMutantsLeft --> Done : allTested

ChecksumTestCmds --> MeasureTestSuite

MeasureTestSuite --> Error : unreliable
MeasureTestSuite --> Coverage : useCov && !hasConstraint
MeasureTestSuite --> LoadSchematas : !useCov

Coverage --> PropagateCov : !error
Coverage --> LoadSchematas : error
PropagateCov --> LoadSchematas

LoadSchematas --> UpdateTimeout

CheckStopCond --> UpdateTimeout
CheckStopCond --> Done : runtime>max

CheckPullRequestMutant --> NextMutant
CheckPullRequestMutant --> Done : allTested

NextSchemata --> SchemataTest : hasSchema
NextSchemata --> Done : !hasSchema && user
NextSchemata --> NextMutant
SchemataTest --> CheckStopCond : done

NextMutant --> CheckTimeout : allTested
NextMutant --> MutationTest
MutationTest --> HandleTestResult : next
MutationTest --> Error : error
MutationTest --> MutationTest

HandleTestResult --> CheckStopCond

CheckTimeout --> Done : unchanged
CheckTimeout --> UpdateTimeout : changed

Done --> SaveMutationScore
SaveMutationScore --> UpdateTestCaseTag
UpdateTestCaseTag --> SaveTestBinary
SaveTestBinary --> Stop

Error --> Stop
@enduml
