//
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import std.stdio;
import unit_threaded;

int main(string[] args) {
    writeln("\nAutomatically generated file build/ut.d");
    writeln(`Running unit tests from dirs ["../source"]`);
    return runTests!("dsrcgen.base", "dsrcgen.c", "dsrcgen.cpp", "dsrcgen.plantuml")(args);
}
