//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand
import std.stdio;
import std.experimental.testing.runner;

int main(string[] args) {
    writeln(`Running unit tests from dirs ["translator", "test", "cpptooling"]`);
    //dfmt off
    return args.runTests!(
                          "cpptooling.analyzer.type",
                          "cpptooling.analyzer.clang.context",
                          "cpptooling.analyzer.clang.type",
                          "cpptooling.analyzer.clang.visitor",
                          "cpptooling.data.representation",
                          "cpptooling.generator.stub.cstub",
                          "cpptooling.utility.clang",
                          "cpptooling.utility.conv",
                          "cpptooling.utility.range",
                          "cpptooling.utility.stack",
                          "test.helpers",
                          "application.app_main",
                          "application.app"
                          );
    //dfmt on
}
