# Documentation: https://docs.codecov.io/docs

coverage:
    precision: 3
    round: down
    range: 80...100

    ignore:
        # not part of Dextool
        - dsrcgen/.*
        - libclang/.*
        - unit-threaded/.*
    status:
        # Learn more at https://codecov.io/docs#yaml_default_commit_status
        project: true
        patch: true
        changes: false

comment: false
