/// @file dextool_default_scheduler.hpp
/// @brief Generated by DEXTOOL_VERSION: v1.1.0-204-gb0fe35e
/// DO NOT EDIT THIS FILE, it will be overwritten on update.
#ifndef I_FUZZ_HPP
#define I_FUZZ_HPP

namespace dextool {

/** A fuzz scenario.
 */
class Fuzz {
public:
    virtual ~Fuzz() {}

    virtual void setup() {}

    virtual void test_body() = 0;

    virtual void teardown() {}

    void run() {
        setup();
        test_body();
        teardown();
    }
};

} //NS:dextool

#endif // I_FUZZ_HPP
