language: d
d:
    - dmd-2.071.1
    - dmd
    # - ldc

os:
    - linux

sudo: required
dist: trusty

notifications:
    email: false

git:
    depth: 1

branches:
    only:
        - master

script: ./travis.sh
