/// @file dextool_default_scheduler.hpp
/// @brief Generated by DEXTOOL_VERSION: v1.1.0-204-gb0fe35e
/// DO NOT EDIT THIS FILE, it will be overwritten on update.
#ifndef dextool_default_scheduler_hpp
#define dextool_default_scheduler_hpp

namespace dextool {

/** A fuzz scenario.
 *
 * Intended to be compatible with gtest.
 * The method casing thus follows the one used in gtest.
 * This is the only exception to the overall name standard.
 */
class Fuzz {
public:
    virtual ~Fuzz();

    virtual void SetUp() {}
    virtual void TestBody() = 0;
    virtual void TearDown() {}

    void Run() {
        SetUp();
        TestBody();
        TearDown();
    }
};

extern void register_fuzz_case(Fuzz *fuzz);

} //NS:dextool
#endif // dextool_default_scheduler_hpp
